spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Zlatanibra9*
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080

# Allow cross-origin from the frontend (served from same host or file://)
spring.web.cors.allowed-origins=*
